### ISSUE TITLE
[Iteration Plan] Alpha Release

### ISSUE THREAD

**Issue by FedericoBruzzone** [FedericoBruzzone/tgt#1]
# Plan Items

**BNF for an item**:  
```ebnf
Item ::= "-" "[" Check? "]" "[" TestAnnotations FeatureAnnotations "]" Description

Check ::= "x"
Description ::= [\d\w\s]+
TestAnnotations ::= [✅❌]
FeatureAnnotations ::= [🏃✋🙅]
```

Test annotations:
| Mark | Description |
|------|-------------|
| ✅    | Tests completed |
| ❌    | No Tests |

Feature annotations:
| Mark | Description |
|------|-------------|
| 🏃    | Work in progress |
| ✋    | Blocked task |
| 🙅    | Not assigned |

# Road Map

## CI/CD
- [x] CI/CD for Linux
- [x] CI/CD for MacOS Intel
- [x] CI/CD for MacOS arm64
- [x] CI/CD for Windows
- [x] CI/CD for release

## Logger
- [x] Add a logger implementation (tracing, tracing-error, tracing-subscriber)
- [x] Fix log timestamp (UTC -> local time)

## Telegram API
- [x] [❌] project configuration for APIs
- [x] [❌] Authentication
- [x] [❌] Receive messages
- [x] [❌] Send messages
- [x] [❌] Handle updates from server
- [x] [❌] Handle logout
- [x] [❌] Handle view message ([function](https://docs.rs/tdlib/latest/tdlib/functions/fn.view_messages.html))
- [x] [❌] Change user status to online and offline using [options](https://core.telegram.org/tdlib/options)

## TUI
- [x] [❌] Handle small window for current components 
- [x] [❌] Create basic components
- [x] [❌] Handle basic events

### Components
**App**
- [x] [❌] Handle login

**Chat List**
- [x] [❌] Add ability to choose a chat
- [x] [❌] Toggle chat list

**Chat Window**
- [x] [❌] Display messages with time of arrival
- [x] [❌] Display if messages has been readed 
- [x] [❌] Edit [link](https://docs.rs/tdlib/latest/tdlib/functions/fn.edit_message_text.html)
- [x] [❌] Delete message
- [x] [❌] Copy message
- [x] [❌] Reply [link](https://docs.rs/tdlib/latest/tdlib/functions/fn.delete_messages.html)
- [x] [❌] Handle message edited [link](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1update_message_edited.html) [link2](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1update_message_content.html)
- [x] [❌] Display message in multiple lines
- [x] [❌] Wrap text

**Prompt Window**
- [x] [❌🙅] Add ability to write text without overflow and multiline

### UI Backend
- [x] [❌] Create basic backend
- [x] [❌] Handle events from `Crossterm`

## Deserialise and parse configuration
- [x] [✅] Logger config
- [x] [✅] Keybindings config (core window)
- [x] [✅] Keybindings config for the components
- [x] [✅] App config
- [x] [✅] Theme config (miss documentation)
- [x] [✅] Telegram config

## Use configuration
- [x] Logger config
- [x] Keybindings config (core window)
- [x] Keybindings config for the components
- [x] App config
- [x] Theme 
- [x] Telegram config

## Release
- [x] Upload to crates.io
- [x] Add install script (cross-platform)
- [x] Add documentation

--- 

For any kind of additional information do not hesitate to [contact us](https://github.com/FedericoBruzzone/tgt?tab=readme-ov-file#contact).
