### ISSUE TITLE
[Iteration Plan] v1.1.0

### ISSUE THREAD

**Issue by FedericoBruzzone** [FedericoBruzzone/tgt#37]
# Plan Items

**BNF for an item**:  
```ebnf
Item ::= "-" "[" Check? "]" "[" TestAnnotations FeatureAnnotations "]" Description

Check ::= "x"
Description ::= [\d\w\s]+
TestAnnotations ::= [✅❌]
FeatureAnnotations ::= [🏃✋🙅]
```

Test annotations:
| Mark | Description |
|------|-------------|
| ✅    | Tests completed |
| ❌    | No Tests |

Feature annotations:
| Mark | Description |
|------|-------------|
| 🏃    | Work in progress |
| ✋    | Blocked task |
| 🙅    | Not assigned |

# Road Map

- [ ] [❌🙅] Add mouse support
- [ ] [❌🙅] Add [Non-Blocking Rolling File Appender](https://docs.rs/tracing-appender/0.2.3/tracing_appender/#non-blocking-rolling-file-appender)
- [ ] [❌🙅] Add single config file for all settings
- [ ] [❌🙅] Add emoji selection to the prompt
- [ ] [❌🙅] Add reply to messages
- [ ] [❌🙅] Add support to other messagest types (Audio, Photo, Files ...)
- [ ] [❌🙅] Add search for messages and chats
- [ ] [❌🙅] Add sound effect on message receive
- [ ] [❌🙅] Add support to archived chat and folder chat
- [ ] [❌🙅] Add command guide pop-up
- [ ] [❌🙅] Add cli
- [ ] [❌🙅] Add docker file, image and upload to github registry
- [ ] [❌🙅] Allow different extension for configuration files
- [ ] [❌🙅] Add search theme config inside sub folder
- [ ] [❌🙅] Flags on tg_context in order to not get elements each frame
- [ ] [❌🙅] Language configuration file
- [ ] [❌🙅] Handle multiple key event for components
- [ ]  [❌🙅] Language configuration file

- [ ] [❌🙅] Show number messages unreaded from each chat
- [ ] Change colorscheme
- [ ] Delete old crates realeses
- [ ] Request an api key form telegram

## Test Telegram API
- [ ] [❌🙅] project configuration for APIs
- [ ] [❌🙅] Authentication
- [ ] [❌🙅] Receive messages
- [ ] [❌🙅] Send messages
- [ ] [❌🙅] Handle updates from server
- [ ] [❌🙅] Handle logout
- [ ] [❌🙅] Handle view message ([function](https://docs.rs/tdlib/latest/tdlib/functions/fn.view_messages.html))
- [ ] [❌🙅] Change user status to online and offline using [options](https://core.telegram.org/tdlib/options)
- [ ] [❌🙅] Display messages with time of arrival
- [ ] [❌🙅] Display if messages has been readed 
- [ ] [❌🙅] Edit message [link](https://docs.rs/tdlib/latest/tdlib/functions/fn.edit_message_text.html)
- [ ] [❌🙅] Delete message
- [ ] [❌🙅] Copy message
- [ ] [❌🙅] Reply message [link](https://docs.rs/tdlib/latest/tdlib/functions/fn.delete_messages.html)
- [ ] [❌🙅] Handle message edited [link](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1update_message_edited.html) [link2](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1update_message_content.html)
- [ ] [❌🙅] Display message in multiple lines
- [ ] [❌🙅] Wrap text

## Test TUI
- [ ] [❌🙅] Handle small window for current components 
- [ ] [❌🙅] Create basic components
- [ ] [❌🙅] Handle basic events

--- 

For any kind of additional information do not hesitate to [contact us](https://github.com/FedericoBruzzone/tgt?tab=readme-ov-file#contact).

**Comment by noizo** [comment]
Please add brew package for linux/macos

**Comment by FedericoBruzzone** [comment]
We will definitely do it for the next release :D

**Comment by FedericoBruzzone** [comment]
We are planning to do this for the next release, not v1.1.0. A small release with a few bug fixes 🫶

**Comment by Xpos587** [comment]
Small release?

**Comment by FedericoBruzzone** [comment]
> Small release?

We can evaluate it. Do you need anything in particular?

**Comment by Xpos587** [comment]
> > Small release?
> 
> We can evaluate it. Do you need anything in particular?

I'm waiting for an update, but if you add at least some support for the extension, then that would be great.

**Comment by FedericoBruzzone** [comment]
What do you mean for "extension"?


> > > Small release?
> > 
> > 
> > We can evaluate it. Do you need anything in particular?
> 
> I'm waiting for an update, but if you add at least some support for the extension, then that would be great.

What do you mean for "extension"?

**Comment by Xpos587** [comment]
Create an internal API to allow users to create their own modules. For example, I want a module that will do automatic mailing every morning at 9:00.

**Comment by Xpos587** [comment]
> What do you mean for "extension"?
> 
> 
> > > > Small release?
> > > 
> > > 
> > > We can evaluate it. Do you need anything in particular?
> > 
> > I'm waiting for an update, but if you add at least some support for the extension, then that would be great.
> 
> What do you mean for "extension"?

An internal API that allows users to create their own modules. For example, I want to write a module that will automatically send a newsletter every morning at 9:00. I also need a module that will automatically take my account offline, and a module that will save deleted messages. I really want to write a module that will analyze my last 100 messages in correspondence and give insights and recommendations.

**Comment by FedericoBruzzone** [comment]
Thank you for your feedback and for
sharing these ideas! However, I’m not sure that adding support for extensions aligns with the primary goals of our tgt project.

The project was designed mainly a tui for Telegram, and introducing an internal API to support extensions like those you mentioned (e.g., newsletters, message analysis, saving deleted messages, etc.) might go beyond its current scope.

That said, if you believe this is an important direction, feel free to propose a more detailed discussion about the benefits and impact such functionality could have for the community or the project. I’m open to evaluating your suggestions, but at the moment, I don’t see this as part of tgt’s core objectives.

**Comment by forshtat** [comment]
Hi! Is it still planned?

**Comment by FedericoBruzzone** [comment]
Hi! Most of the stuff has been implemented. Did you want to develop something?

**Comment by forshtat** [comment]
> Hi! Most of the stuff has been implemented. Did you want to develop something?

Glad to hear. Well, if it helps I definitely could.
